### ISSUE TITLE
Sample "ContentProviderPagingKotlin" crashes

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/storage-samples#16]
![image](https://user-images.githubusercontent.com/5357526/64481184-6db4fa00-d1df-11e9-9686-cf22bdf16f99.png)

2019-09-08 02:20:34.585 28158-28158/com.example.android.contentproviderpaging E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.contentproviderpaging, PID: 28158
    java.lang.RuntimeException: Unable to get provider com.example.android.contentproviderpaging.ImageProvider: java.lang.ClassNotFoundException: Didn't find class "com.example.android.contentproviderpaging.ImageProvider" on path: DexPathList[[zip file "/data/app/com.example.android.contentproviderpaging-OXltTdAm2A1a4Aqc-7OZuA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.android.contentproviderpaging-OXltTdAm2A1a4Aqc-7OZuA==/lib/arm64, /system/lib64, /system/product/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6988)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.android.contentproviderpaging.ImageProvider" on path: DexPathList[[zip file "/data/app/com.example.android.contentproviderpaging-OXltTdAm2A1a4Aqc-7OZuA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.android.contentproviderpaging-OXltTdAm2A1a4Aqc-7OZuA==/lib/arm64, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6972)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by volkansahin45** [comment]
This issue should be fixed by #42. @nic0lette

**Comment by AndroidDeveloperLB** [comment]
Tested now. Seems to crash after some scrolling. At around item 110.
Tested on Pixel 2 with Android Q.
Why close this ?
Look at the attached video.

[device-2019-11-04-095345.zip](https://github.com/android/storage-samples/files/3803007/device-2019-11-04-095345.zip)

Maybe OOM?

**Comment by volkansahin45** [comment]
It' an another issue. This one has fixed. If you have any other problems i think you should open another issues with process steps. @AndroidDeveloperLB

**Comment by AndroidDeveloperLB** [comment]
Another issue? It still crashes...
If you want a new report, here:
https://github.com/android/storage-samples/issues/43

**Comment by volkansahin45** [comment]
Is there any problem now? @AndroidDeveloperLB

**Comment by AndroidDeveloperLB** [comment]
@volkansahin45 Have you checked the link? I already written there is an issue.

**Comment by volkansahin45** [comment]
Yes that should be fixed, too. can you check?

**Comment by AndroidDeveloperLB** [comment]
@volkansahin45 Please continue to write there. You wanted me to create a new issue after all.
